
package com.bigdata.ws.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-13T11:53:34.240+08:00
 * Generated source version: 3.1.12
 * 
 */
 
public class CustomerTrendsWebServicePortServer{

    protected CustomerTrendsWebServicePortServer() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CustomerTrendsWebServicePortImpl();
        String address = "http://localhost:8580/cxf-webservice/cxf-ws/ctWS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CustomerTrendsWebServicePortServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
