package com.bigdata.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-13T11:53:34.236+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.bigdata.com/", name = "CustomerTrendsWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CustomerTrendsWebService {

    @WebResult(name = "return", targetNamespace = "http://ws.cxf.bigdata.com/", partName = "return")
    @WebMethod
    public java.lang.Object showCustomertrends();
}
