package com.bigdata.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-13T11:53:34.290+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "CustomerTrendsWebServiceService", 
                  wsdlLocation = "http://localhost:8580/cxf-webservice/cxf-ws/ctWS?wsdl",
                  targetNamespace = "http://ws.cxf.bigdata.com/") 
public class CustomerTrendsWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.cxf.bigdata.com/", "CustomerTrendsWebServiceService");
    public final static QName CustomerTrendsWebServicePort = new QName("http://ws.cxf.bigdata.com/", "CustomerTrendsWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8580/cxf-webservice/cxf-ws/ctWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerTrendsWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8580/cxf-webservice/cxf-ws/ctWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerTrendsWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerTrendsWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerTrendsWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerTrendsWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerTrendsWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerTrendsWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CustomerTrendsWebService
     */
    @WebEndpoint(name = "CustomerTrendsWebServicePort")
    public CustomerTrendsWebService getCustomerTrendsWebServicePort() {
        return super.getPort(CustomerTrendsWebServicePort, CustomerTrendsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerTrendsWebService
     */
    @WebEndpoint(name = "CustomerTrendsWebServicePort")
    public CustomerTrendsWebService getCustomerTrendsWebServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerTrendsWebServicePort, CustomerTrendsWebService.class, features);
    }

}
