
package com.bigdata.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-13T11:53:34.210+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class CustomerTrendsWebServicePortClient {
	
	private static Logger logger = LogManager.getLogger(CustomerTrendsWebServicePortClient.class);

    private static final QName SERVICE_NAME = new QName("http://ws.cxf.bigdata.com/", "CustomerTrendsWebServiceService");

    private CustomerTrendsWebServicePortClient() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerTrendsWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerTrendsWebServiceService ss = new CustomerTrendsWebServiceService(wsdlURL, SERVICE_NAME);
        CustomerTrendsWebService port = ss.getCustomerTrendsWebServicePort();  
        
        {
        System.out.println("调用最近12个月的客户趋势数据接口......");
        long startTime = System.currentTimeMillis();
        java.lang.Object _showCustomertrends__return = port.showCustomertrends();
        long endTime = System.currentTimeMillis();
        logger.info("调用最近12个月的客户趋势数据接口，用时： " + (endTime - startTime) + "ms。");
        System.out.println("showCustomertrends.result=" + _showCustomertrends__return);


        }

        System.exit(0);
    }

}
